@extends('layouts.app')

@section('content')
<div class="space-y-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">Periode pembelajaran sekolah</p><h2 class="mt-1 text-2xl font-bold text-slate-900">Tahun Ajaran</h2></div><span class="rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700">{{ $academicYears->total() }} periode</span></div>
    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
        <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Periode</th><th class="px-5 py-3">Rentang</th><th class="px-5 py-3">Semester</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($academicYears as $year)<tr><td class="px-5 py-4"><div class="font-semibold text-slate-900">{{ $year->name }}</div>@if($year->is_active)<span class="mt-1 inline-flex rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-medium text-emerald-700">Aktif</span>@endif</td><td class="px-5 py-4 text-slate-600">{{ $year->start_date->format('d M Y') }} - {{ $year->end_date->format('d M Y') }}</td><td class="px-5 py-4 text-slate-600">{{ $year->semesters_count }} semester · {{ $year->school_classes_count }} kelas</td><td class="px-5 py-4 text-right">@if(!$year->is_active)<div class="flex justify-end gap-2"><form method="POST" action="{{ route('admin.academic-years.activate', $year) }}">@csrf @method('PATCH')<button class="rounded-lg border border-indigo-200 px-3 py-1.5 text-xs font-semibold text-indigo-700 hover:bg-indigo-50">Aktifkan</button></form><form method="POST" action="{{ route('admin.academic-years.destroy', $year) }}" onsubmit="return confirm('Hapus tahun ajaran ini?')">@csrf @method('DELETE')<button class="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-700 hover:bg-rose-50">Hapus</button></form></div>@else<span class="text-xs text-slate-400">Periode berjalan</span>@endif</td></tr>@empty<tr><td colspan="4" class="px-5 py-12 text-center text-sm text-slate-500">Belum ada tahun ajaran.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $academicYears->links() }}</div></section>
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-semibold text-slate-900">Tambah tahun ajaran</h3><form method="POST" action="{{ route('admin.academic-years.store') }}" class="mt-5 space-y-4">@csrf<div><label class="text-xs font-semibold text-slate-600">Nama periode</label><input name="name" value="{{ old('name') }}" placeholder="2026/2027" required class="mt-1 w-full rounded-lg border-slate-300 text-sm"></div><div class="grid grid-cols-2 gap-3"><div><label class="text-xs font-semibold text-slate-600">Mulai</label><input type="date" name="start_date" required class="mt-1 w-full rounded-lg border-slate-300 text-sm"></div><div><label class="text-xs font-semibold text-slate-600">Selesai</label><input type="date" name="end_date" required class="mt-1 w-full rounded-lg border-slate-300 text-sm"></div></div><label class="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" name="is_active" value="1" class="rounded border-slate-300 text-indigo-600"> Jadikan periode aktif</label><button class="w-full rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">Simpan periode</button></form></section>
    </div>
</div>
@endsection
