@extends('layouts.app')
@section('content')
<div class="space-y-6">
    <header><p class="text-sm font-medium text-blue-700">Kalender akademik</p><h1 class="mt-1 text-2xl font-bold text-slate-900">Jadwal Ujian per Siswa</h1><p class="mt-1 text-sm text-slate-500">Atur Ujian Praktik, Ujian Sekolah, PTS, dan PAS berdasarkan kelas, siswa, serta mata pelajaran.</p></header>
    <form method="GET" class="flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-4"><label class="text-sm font-medium text-slate-700">Filter kelas<select name="school_class_id" onchange="this.form.submit()" class="mt-1 min-w-56 rounded-lg border-slate-300">@foreach($classes as $schoolClass)<option value="{{ $schoolClass->id }}" @selected($classId === $schoolClass->id)>{{ $schoolClass->name }} · {{ $schoolClass->academicYear?->name }}</option>@endforeach</select></label></form>
    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
        <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-blue-50 text-xs uppercase text-blue-950"><tr><th class="px-4 py-3">Waktu / Ujian</th><th class="px-4 py-3">Siswa / Kelas</th><th class="px-4 py-3">Mata Pelajaran</th><th class="px-4 py-3">Tempat</th><th class="px-4 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($examSchedules as $exam)<tr><td class="px-4 py-3"><p class="font-semibold text-slate-900">{{ $exam->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $exam->starts_at->format('d/m/Y H:i') }}–{{ $exam->ends_at->format('H:i') }} · {{ $examTypes[$exam->exam_type] }}</p></td><td class="px-4 py-3">{{ $exam->student?->name }}<p class="text-xs text-slate-500">{{ $exam->schoolClass?->name }}</p></td><td class="px-4 py-3">{{ $exam->subject?->name }}</td><td class="px-4 py-3">{{ $exam->room ?: '—' }}</td><td class="px-4 py-3"><details><summary class="cursor-pointer font-semibold text-blue-800">Ubah</summary><form method="POST" action="{{ route(auth()->user()->hasRole(['admin','super_admin']) ? 'admin.exam-schedules.update' : 'teacher.exam-schedules.update', $exam) }}" class="absolute z-10 mt-2 grid w-72 gap-2 rounded-xl border bg-white p-4 shadow-xl">@csrf @method('PUT')<input type="hidden" name="school_class_id" value="{{ $exam->school_class_id }}"><select name="student_id" required class="rounded-lg border-slate-300">@foreach($students as $student)<option value="{{ $student->id }}" @selected($exam->student_id === $student->id)>{{ $student->name }}</option>@endforeach</select><select name="subject_id" required class="rounded-lg border-slate-300">@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected($exam->subject_id === $subject->id)>{{ $subject->name }}</option>@endforeach</select><select name="exam_type" class="rounded-lg border-slate-300">@foreach($examTypes as $key => $label)<option value="{{ $key }}" @selected($exam->exam_type === $key)>{{ $label }}</option>@endforeach</select><input name="title" value="{{ $exam->title }}" required class="rounded-lg border-slate-300"><input type="datetime-local" name="starts_at" value="{{ $exam->starts_at->format('Y-m-d\TH:i') }}" required class="rounded-lg border-slate-300"><input type="datetime-local" name="ends_at" value="{{ $exam->ends_at->format('Y-m-d\TH:i') }}" required class="rounded-lg border-slate-300"><input name="room" value="{{ $exam->room }}" placeholder="Ruang" class="rounded-lg border-slate-300"><textarea name="notes" placeholder="Catatan" class="rounded-lg border-slate-300">{{ $exam->notes }}</textarea><button class="rounded-lg bg-blue-950 p-2 font-semibold text-white">Simpan</button></form><form method="POST" action="{{ route(auth()->user()->hasRole(['admin','super_admin']) ? 'admin.exam-schedules.destroy' : 'teacher.exam-schedules.destroy', $exam) }}" onsubmit="return confirm('Hapus jadwal ujian?')" class="mt-2">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-700">Hapus</button></form></details></td></tr>
        @empty<tr><td colspan="5" class="px-4 py-10 text-center text-slate-500">Belum ada jadwal ujian untuk kelas ini.</td></tr>@endforelse
        </tbody></table></div><div class="p-4">{{ $examSchedules->withQueryString()->links() }}</div></section>
        <section class="h-fit rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-900">Tambah jadwal ujian</h2>@if($classId)<form method="POST" action="{{ route(auth()->user()->hasRole(['admin','super_admin']) ? 'admin.exam-schedules.store' : 'teacher.exam-schedules.store') }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="school_class_id" value="{{ $classId }}"><label class="block text-sm">Siswa<select name="student_id" required class="mt-1 w-full rounded-lg border-slate-300"><option value="">Pilih siswa</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->name }}</option>@endforeach</select></label><label class="block text-sm">Mata pelajaran<select name="subject_id" required class="mt-1 w-full rounded-lg border-slate-300"><option value="">Pilih mata pelajaran</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }}</option>@endforeach</select></label><label class="block text-sm">Jenis<select name="exam_type" required class="mt-1 w-full rounded-lg border-slate-300">@foreach($examTypes as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><label class="block text-sm">Nama ujian<input name="title" required class="mt-1 w-full rounded-lg border-slate-300" placeholder="Contoh: Ujian Praktik IPA"></label><label class="block text-sm">Mulai<input type="datetime-local" name="starts_at" required class="mt-1 w-full rounded-lg border-slate-300"></label><label class="block text-sm">Selesai<input type="datetime-local" name="ends_at" required class="mt-1 w-full rounded-lg border-slate-300"></label><label class="block text-sm">Ruang<input name="room" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="block text-sm">Catatan<textarea name="notes" rows="2" class="mt-1 w-full rounded-lg border-slate-300"></textarea></label><button class="w-full rounded-lg bg-blue-950 px-4 py-2.5 text-sm font-semibold text-white">Simpan jadwal</button></form>@else<p class="mt-3 text-sm text-slate-500">Belum ada kelas yang dapat dikelola.</p>@endif</section>
    </div>
</div>
@endsection
